on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - name: Check OS and Architecture
        run: |
          systeminfo
          echo Processor Architecture: %PROCESSOR_ARCHITECTURE%

      - name: Check Installed .NET Framework Versions
        run: reg query "HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP" /s

      - name: Create Dotnet Web Application (Model-View-Controller)
        run: dotnet new mvc --name MyDotnetApp --output .

      - run: dotnet add package RabbitMQ.Client

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "oc-2"
          git config --global user.email "185859974+oc-2@users.noreply.github.com"
          git add -A
          git commit -m "Add dotnet app" --allow-empty
          git push origin HEAD:main