on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check OS and Architecture
        run: |
          systeminfo
          echo Processor Architecture: %PROCESSOR_ARCHITECTURE%

      - name: Download .NET Framework 4.7.2 Installer
        run: curl -L -o "${{ github.workspace }}\\NDP472-DevPack-ENU.exe" "https://go.microsoft.com/fwlink/?linkid=874338"

      - name: Verify Installer
        run: dir "${{ github.workspace }}\\NDP472-DevPack-ENU.exe"

      - name: Install .NET Framework 4.7.2
        shell: pwsh
        run: |
          echo "Installing .NET Framework 4.7.2..."
          Start-Process -FilePath "${{ github.workspace }}\\NDP472-DevPack-ENU.exe" -ArgumentList "/quiet", "/norestart" -NoNewWindow -Wait

      - name: Delete Installer File
        shell: pwsh
        run: if (Test-Path "D:\a\MyDotnetApp\MyDotnetApp\NDP472-DevPack-ENU.exe") { Remove-Item "D:\a\MyDotnetApp\MyDotnetApp\NDP472-DevPack-ENU.exe" -Force }

      - name: Check Installed .NET Framework Versions
        run: reg query "HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP" /s

      - name: Create Dotnet Webapp
        run: dotnet new webapp --name MyDotnetApp --output .

      - run: dotnet add package RabbitMQ.Client --framework net9.0

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "oc-2"
          git config --global user.email "185859974+oc-2@users.noreply.github.com"
          git add -A
          git commit -m "Add dotnet app" --allow-empty
          git push origin HEAD:main