on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Environment
      run: |
        echo "Current Directory:"
        pwd
        echo "Files in Directory:"
        dir

    - name: Download .NET Framework 4.7.2 Installer
      run: |
        curl -L -o .\{ github.workspace }\NDP472-DevPack-ENU.exe "https://download.visualstudio.microsoft.com/download/pr/d0c6a9a4-35a3-4f8c-94e8-83a20de190e7/7E798D56A36BB5A34DFAF2A9D5915FD49AB41DE83F4C57C8BABB5F76D5C9E7DF/ndp472-devpack-enu.exe"

    - name: Install .NET Framework 4.7.2
      run: |
        echo Installing .NET Framework 4.7.2...
        D:\a\{ github.workspace }\NDP472-DevPack-ENU.exe /quiet /norestart

    - name: Create Dotnet App
      run: dotnet new mvc --name MyDotnetApp --output .

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Commit and Push
      run: |
        git config --global user.name "oc-2"
        git config --global user.email "185859974+oc-2@users.noreply.github.com"
        git add .
        git commit -m "Updated: $(date -u +"%D %T %Z")" --allow-empty
        git push origin HEAD:main
