on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '4.7.2'
          cache: true

      - name: Create Dotnet App
        run: dotnet new mvc --name MyDotnetApp --output ${{ github.workspace }}

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "oc-2"
          git config --global user.email "185859974+oc-2@users.noreply.github.com"
          git add -A
          git commit -m "Add dotnet app" --allow-empty
          git push origin HEAD:main